const reviewSchema =  new mongoose.Schema({
  "_id": ObjectId,  // Auto-generated by MongoDB
     "product_id": Number,
     "rating": Number,
     "summary": String,
     "recommend": Boolean,
     "response": String || null,
     "body": String,
     "date": Date,
     "reviewer_name": String,
     "helpfulness": Number,
     "reported": Boolean,
     "response": String,
     "photos": [
         {
             "id": Number,
             "url": String
         }
     ],
     "characteristics_reviews": [
         {
             "name": String,
             "value": Number
         }
     ]
 })